export const products = [
    {
        id: 1,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/03/product_gear_speaker_1_1-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/03/product_gear_speaker_1_2-450x450.jpg',
        thumbnail1: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/03/product_gear_speaker_1_4-655x655.jpg',
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/03/product_gear_speaker_1_3-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/03/product_gear_speaker_1_2-655x655.jpg",
        thumbnail4:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/03/product_gear_speaker_1_1-655x655.jpg",
        category: 'Bluetooth Speakers',
        title: 'Klipsch R-120SW Powerful Detailed Home Speaker – Unit',
        rating: 3,
        originalPrice: 139.00,
        discountedPrice: 129.00,
        color:'black',
    },
    {
        id: 2,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_32_1-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_32_3-450x450.jpg',
        thumbnail1:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_32_1-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_32_2-150x150.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_32_3-150x150.jpg",
        category: 'ROBOT CLEAN',
        title: 'MIJIA Robot Vacuum 1T Sweeping Wet Mopping Cleaner For Home Dust Sterilize 3000PA Cyclone Suction WIFI APP Smart Planned',
        rating: 5,
        originalPrice: 579.99,
        discountedPrice: 579.99,
        color:'black',
    },
    {
        id: 3,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_31_1-150x150.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_31_2-150x150.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_31_3-150x150.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_31_2-150x150.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_31_4-150x150.jpg",
        thumbnail4:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_31_1-655x655.jpg",
        category: 'TABLETS',
        title: 'Teclast M40 10.1 Inch Android 10.0 Tablet PC UNISOC T618 Octa Core 6GB RAM 128GB ROM 4G LTE Full HD',
        rating: 5,
        originalPrice: 307.60,
        discountedPrice: 289.95,
        color:'red',
    },
    {
        id: 4,
        imageSrc:'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_30_1-655x655.jpg',
        hoverImage:'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_30_2-655x655.jpg',
        thumbnail1:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_30_1-655x655.jpg",
        thumbnail2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_30_2-150x150.jpg",
        thumbnail3:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_30_3-150x150.jpg",
        thumbnail4:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_30_4-655x655.jpg",
        category: 'FEATURED PHONES',
        title: 'UMIDIGI Power 3 6150mAh 6.53 Inch FHD+ 4GB Global Version Helio P60 64GB ROM Quad Camera Android 10 Face ID Smartphone',
        rating: 5,
        originalPrice: 200.00,
        discountedPrice: 210.00,
        color:'red',
    },
    {
        id: 5,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_29_1-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_29_2-655x655.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_29_2-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_29_1-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_29_3-655x655.jpg",
        thumbnail4:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_29_4-655x655.jpg",
        category: 'MP3 PLAYERS',
        title: 'ZY418 Ultra-Thin Sport MP3 MP4 Music Player',
        rating: 5,
        originalPrice: 50.00,
        discountedPrice: 45.00,
        color:'black',
    },
    {
        id: 6,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_28_1-150x150.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_28_2-150x150.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_28_1-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_28_2-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_28_3-655x655.jpg",
        category: 'Bluetooth Speakers',
        title: 'Soundcore Flare Mini Bluetooth Speaker Outdoor Bluetooth Speaker IPX7 Waterproof',
        rating: 5,
        originalPrice: 100.00,
        discountedPrice: 77.08,
    },
    {
        id: 7,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_27_1-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_27_2-655x655.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_27_1-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_27_2-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_27_3-655x655.jpg",
        category: 'SECURITY & PROTECTION',
        title: 'DIDSeth Pan Tilt Security Light Camera Full HD 1080P Wireless Wi-Fi IP Camera Home Dome Surveillance Cameras',
        rating: 5,
        originalPrice: 49.00,
        discountedPrice: 48.00,
    },
    {
        id: 8,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_26_3-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_26_1-655x655.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_26_3-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_26_1-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_26_2-655x655.jpg",
        thumbnail4: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_26_4-655x655.jpg",
        category: 'ROBOT CLEAN',
        title: 'VIOMI V2 Pro LDS Sensor 2 In 1 Sweeping Mopping Robot Wet And Dry Vacuum Cleaner 2100Pa Strong Suction Self-Charging',
        rating: 5,
        originalPrice: 600.00,
        discountedPrice: 575.00,
    },
    {
        id: 9,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_25_1-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_25_2-655x655.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_25_1-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_25_2-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_25_3-655x655.jpg",
        thumbnail4: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_25_4-655x655.jpg",
        category: 'COMPUTERS & LAPTOPS',
        title: 'Teclast F7 Plus 14.1 Inch Notebook Intel N4100 8GB RAM 256GB SSD – Platinum 8GB+256GB',
        rating: 5,
        originalPrice: 700.90,
        discountedPrice: 696.90,
    },
    {
        id: 10,
        imageSrc: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_24_3-655x655.jpg',
        hoverImage: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_24_1-655x655.jpg',
        thumbnail1: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_24_3-655x655.jpg",
        thumbnail2: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_24_1-655x655.jpg",
        thumbnail3: "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_supergear_02_3-655x655.jpg",
        thumbnail4:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_24_4-655x655.jpg",
        category: 'SMART HEALTH WATCH',
        title: 'Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band',
        rating: 5,
        originalPrice: 85.00,
        discountedPrice: 79.00,
    },
];


export const getThumbnails = (selectedProductId) => {
    const selectedProduct = products.find(product => product.id === selectedProductId);

    if (!selectedProduct) {
        return [];
    }

    return [
        { id: selectedProduct.id, thumbnail: selectedProduct.thumbnail1 },
        { id: selectedProduct.id, thumbnail: selectedProduct.thumbnail2 },
        { id: selectedProduct.id, thumbnail: selectedProduct.thumbnail3 },
        { id: selectedProduct.id, thumbnail: selectedProduct.thumbnail4 },
    ];
};


export const slides = [
    {
        id: 1,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_geart_01-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'Setup your Surround sound speaker',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_07-870x500.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    },
    {
        id: 2,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_geart_02-427x250.jpg',
        category: 'LIFE STYLE',
        title: 'Hook up a receiver for you Home Theater',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_supergear_11_4-800x540.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    }, {
        id: 3,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_geart_03-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'Top most Comfortable Headphones',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_07-870x500.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    },
    {
        id: 4,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_04-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'CUBOT X20 PRO: iPhone 11 rear camera design will be available for sale',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_08-870x500.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    }, {
        id: 5,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_05-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'CUBOT X20 PRO: iPhone 11 rear camera design will be available for sale on SuperGear',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_supergear_12_4.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    }, {
        id: 6,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_06-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'Get Teclast T30 tablet at an unexpected price at SuperGear',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_04-870x540.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    },
    {
        id: 7,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_07-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'Amazfit GTR Titanium Edition and Austrian Zircon Version will Officially go on Exclusive Global Sale',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_geart_01-870x540.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    }, {
        id: 8,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_08-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'Don’t miss out! Xiaomi Mi Note 10 exclusive global launch hit',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_10-870x500.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    }, {
        id: 9,
        imageUrl: 'https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_10-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'Do you want a stylish smartphone with a pop-up camera for budget price? Take the Elephone PX (2019)',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_04-870x500.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    },
    {
        id: 10,
        imageUrl: ' https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/home-hero-banner-427x250.jpg',
        category: 'TECHNOLOGY',
        title: 'DJI Mavic Mini: the ultra-light consumer drone for beginner sale',
        description1:"Officially available for pre-order in the U.S. today on the Valentino Beauty site, the opulent multi-piece collection draws inspiration from Valentino's storied 61-year history, imbuing each luxe piece with the uniqueness, extravaganza, and experimentation that defines its haute couture collections.",
        description2:"But don't let those couture connotations fool you. Rest assured, there's nothing stuffy, exclusive, or conventional about this cosmetic lineup.",
        description3:"Designed under the discerning eye of Pierpaolo Piccioli, Maison Valentino's Creative Director, and developed in partnership with L'Oreal Paris, each of the versatile, multi-finish products is designed to speak to the freedom of expression and individuality that lies at the core of the brand, states the press release. As such, you can expect a wide array of products and shades that work across all genders, ages, and cultures, each one intended to evoke freedom, creativity, and the signature modern glamour that Valentino does oh so well.",
        headingPrimary:"The Inspiration Behind Valentino Beauty",
        headingDescription:"To celebrate this expressive and inclusive initiative, Piccioli even ventured behind the camera, shooting 16 models from varied backgrounds, all united by the Rosso Valentino lipstick, forming what he describes as a Valentino chorus.",
        imageUrl2:"https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/blog_gear_09-870x500.jpg",
        headingDescription2:"Beauty is a complexity resolved through love. Beauty is democratic. I look at the identity of each individual, the uniqueness that encloses diversity and inclusivity, he adds. Beauty is about grace. Grace is something that you cannot describe; it is a perception. Beauty is something that gives me emotion. It is a connection.",
        blockquote:"“I try as much as possible to give you a great basic product and what comes out, I feel, is really amazing.”",
        headingDescription3:"Excited? So are we. Ahead, check out the ten products our editors will most certainly be adding to cart today, along with some additional details about how to shop each one.The Valentino Beauty collection is now available for pre-order through the Valentino site, with delivery expected by early July."
    },
];