import { Inter } from 'next/font/google';
import "./styles/globals.css";
import Headers from './components/Headers/Headers';
import Footer from './components/Footer/Footer';
import SideBar from './components/SideBar/SideBar';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <SideBar className="z-40" />
        <Headers />
        {children}
        <Footer />
      </body>
    </html>
  )
}
